### ISSUE TITLE
1. Implementation of create/store/view/delete functions

### ISSUE THREAD

**Issue by aligungr** [primetech495/RecipeJungle-Mobil#1]
User should be able to create/store/view/delete recipes from the mobile application. User can store the recipes and access them whenever needed to cook or start planning cooking.

Subissues for the mobile application:
- [x]  Implementation of the create function( #9  ) 
- [x]  Implementation of the store function( #11  ) 
- [x]  Implementation of the view function(#8  )
- [x]  Implementation of the delete function(#10  )
